### ISSUE TITLE
API tool can't properly distinguish path params from query params in MVC routes

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1069]
The below MVC route mapping works as expected
```kotlin
@Path("/:name")
fun get(name: String, foo: String, bar: Optional<String>) {
    // do something
}
```
- `/paul` -> HTTP 404 as `bar` is missing
- `/paul?foo=foo` -> HTTP 200, `name` and `foo` populated
- `/?foo=foo` -> HTTP 404
- `/paul?foo=foo&bar=bar` -> HTTP 200, `name`, `foo` and `bar` populated

The APITool, however, doesn't get it. In fact the Swagger isn't even valid:

```yaml
paths:
  '/{name}':
    get:
      parameters:
        - name: arg0    # <-- should be 'name'
          in: query     # <-- should be a path param
          required: true
          type: string
        - name: arg1    # <-- should be 'foo'
          in: query
          required: true
          type: string
        - name: arg2    # <-- should be 'bar'
          in: query
          required: false
          type: string
```

**Update**
Making use of `@Named` in the method signature fixes the arg naming issue:
```kotlin
fun get(@Named("name") name: String, @Named("foo") foo: String, @Named("bar") bar: Optional<String>)
```
