### ISSUE TITLE
API tool does not detect required model properties

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1072]
As [discussed on Gitter](https://gitter.im/jooby-project/jooby?at=5ae08a3d1130fe3d3616110d)...

The following Kotlin data class should lead to a Swagger model definition that declares the `name` as required.

```kotlin
data class Person(
    val name: String,
    val firstname: String?)
```
Expected Swagger model:

```yaml
Person:
  type: object
  required: 
    - name
  properties:
    name:
      type: string
    firstname:
      type: string
```
The Kotlin byte code reveals the important difference between `name` and `firstname`

```
// access flags 0x12
private final Ljava/lang/String; name
@Lorg/jetbrains/annotations/NotNull;() // invisible

// access flags 0x12
private final Ljava/lang/String; firstname
@Lorg/jetbrains/annotations/Nullable;() // invisible
```

While both are `val`s and thus final and contributing to an immutable `Person` only `name` is not nullable. As I[ found out last year](https://stackoverflow.com/q/45575493/131929) if an OpenAPI model property is declared as `required` it must NOT be null i.e. if it's nullable it can't be required.
