### ISSUE TITLE
API tool falsely flags an optional parameter as required

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1074]
As discussed [on Gitter](https://gitter.im/jooby-project/jooby?at=5ae1e7641130fe3d361cc378)...

The first optional parameter in the following declaration is flagged by the API tool as mandatory:

```kotlin
val page = param("page").toOptional(Integer::class) // uses org.jooby.toOptional
val pageSize = param("page-size").toOptional(Integer::class.java)
```

```yaml
parameters:
- name: page
  in: query
  required: true  # <- should be false
  type: object    # <- should be integer
- name: page-size
  in: query
  required: false
  type: integer
  format: int32
```

The Kotlin bytecode for the two lines:

```
    LINENUMBER 13 L2
    ALOAD 1
    LDC "page"
    INVOKEINTERFACE org/jooby/Request.param (Ljava/lang/String;)Lorg/jooby/Mutant;
    DUP
    LDC "param(\"page\")"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull (Ljava/lang/Object;Ljava/lang/String;)V
    LDC Ljava/lang/Integer;.class
    INVOKESTATIC kotlin/jvm/internal/Reflection.getOrCreateKotlinClass (Ljava/lang/Class;)Lkotlin/reflect/KClass;
    INVOKESTATIC org/jooby/JoobyKt.toOptional (Lorg/jooby/Mutant;Lkotlin/reflect/KClass;)Ljava/util/Optional;
    ASTORE 3
   L3



    LINENUMBER 14 L3
    ALOAD 1
    LDC "page-size"
    INVOKEINTERFACE org/jooby/Request.param (Ljava/lang/String;)Lorg/jooby/Mutant;
    LDC Ljava/lang/Integer;.class
    INVOKEINTERFACE org/jooby/Mutant.toOptional (Ljava/lang/Class;)Ljava/util/Optional;
    ASTORE 4
   L4
```

API tool also needs to look for `org/jooby/JoobyKt.toOptional (Lorg/jooby/Mutant;Lkotlin/reflect/KClass;)`
