### ISSUE TITLE
API tool needs to ensure operationIds are unique across all routes

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1075]
Swagger files with non-unique `operationId`s are invalid. I don't fully understand API tool's operation-id-generation strategy but it's pretty easy to end up with duplicate ids.

```kotlin
path("/v2"){
    path("/orders") {
        get {
            listOf("order-1", "order-2")
        }
    }
    path("/products") {
        get {
            listOf("product-1", "product-2")
        }
    }
}
```

```yaml
/v2/orders:
  get:
    tags:
      - V2
    operationId: getV2
    ...
/v2/products:
  get:
    tags:
      - V2
    operationId: getV2
```

The workaround is, I believe, is to set the `operationId` [manually for every route](https://jooby.org/doc/apitool/#API-tool-advanced-usage):

```kotlin
use(ApiTool()
    .modify({ r -> r.pattern() == "/v2/orders" }) { route ->
        // now what?
    }
)
```
