### ISSUE TITLE
API tool fails when single global consumes definition is set

### ISSUE THREAD

**Issue by marcelstoer** [jooby-project/jooby#1076]
The contract I'm programming against is as follows:

```yaml
...
basePath: /v2
consumes:
- "*/*"    # <- you can argue whether this is sensible but it is what it is...
produces:
- application/json
tags:
...
```

Hence, to reflect this in Jooby I use the following (Kotlin) code:

```kotlin
use(ApiTool()
    .swagger("/apidocs") { swagger ->
        swagger.consumes(listOf(MediaType.all.toString())) // <- immutable list of a single media type
    }
```

The API tool fails to build the Swagger definition because it tries to forcefully add its default media type to the global but immutable list. Excerpt from [`SwaggerBuilder:435`](https://github.com/jooby-project/jooby/blob/master/modules/jooby-apitool/src/main/java/org/jooby/internal/apitool/SwaggerBuilder.java#L435) (fails on 437);

```java
    List<String> consumes = mediaTypes.apply(RouteMethod::consumes);
    if (consumes.size() == 0) {
      swagger.consumes(MediaType.json.name());
    } else if (consumes.size() == 1) {
      swagger.consumes(consumes);
    }
```
