### ISSUE TITLE
openapi: regex from path variable is ignored it

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#1585]
```
get("/user/{id:[0-9]+}", ..)
```

Must generates:

```yaml
  /user/{id}:
    get:
      operationId: getUserId09
      parameters:
      - name: id
        in: path
        required: true
        schema:
          pattern: '[0-9]+'
          type: integer
          format: int32
```
