### ISSUE TITLE
better route spec

### ISSUE THREAD

**Issue by jknack** [jooby-project/jooby#758]
Some thoughts:

- make truly optional source code. Today it is a mix.
- create/define alternative way to add metadata (doc, params and return type)

More?

**Comment by ajcamilo** [comment]
Have a way to specify explicit data type specification, for example.

If I have a return class like this:

```
public class User {
  public UUID id;
  public username;
}
```

The RAML plugin, will collect metadata from UUID class, but in RAML, the uuid type should be:

```
types:
  uuid:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
```

to resolve this, there should be a way to define explicitly that UUID.class should not be "parsed" by the default parser, but have a specific "metadata".
