### ISSUE TITLE
ApiTool does not handle Upload correctly on mvc routes

### ISSUE THREAD

**Issue by hwacookie** [jooby-project/jooby#958]
According to @jknack , a "Upload" parameter should be generated as a parameter of type "file", so for this input...
```
	@POST
	@Path("/upload_A")
	public String upload_A(final Upload myfile) throws IOException {
           <...>
        }
```
ApiTool should generate this swagger.yml:

```
paths:
  /api/filesystem/upload_A:
    post:
      tags:
      - "Filesystem"
      operationId: "/FilesystemController.upload_A"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "myfile"
        in: "formData"
        required: true
        type: file
        <...>
```
However, right now the result that ApiTool generates looks like:
```
  /api/filesystem/upload_A:
    post:
      tags:
      - "Filesystem"
      operationId: "/FilesystemController.upload_A"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "myfile"
        in: "formData"
        required: true
        type: "ref"
        <...>
```
This causes swagger-codegen to throw an NPE because of an empty ref.
Also, the generated client now looks like...
```
    public String filesystemControllerUploadA(Object myfile) throws ApiException {
        // ...
    }
```
which is rather useless, "myfile" should be of type "File", not "Object".

If I manually fix the .yml file, I can use swagger-codegen to create a valid and working client.
